.SET SESSION TRANSACTION ANSI
.SET FORMAT ON
.SET INDICDATA OFF
.LOGON 127.0.0.1/dbc,dbc

 DATABASE USER_DBC;

.IMPORT DATA FILE = 'C:\Users\rgopidi\IMPORT_DATA_PARTY1.txt'
.REPEAT *
USING (
    ORG VARCHAR(30),
    PARTY_ID INTEGER,
    PARTY_FST_NM VARCHAR(30),
    PARTY_LST_NM VARCHAR(30),
    PARTY_LOC VARCHAR(30),
    PARTY_INCOME INTEGER,
    JDATE DATE
)
INSERT INTO PARTY1 
VALUES (
    :ORG,
    :PARTY_ID,
    :PARTY_FST_NM,
    :PARTY_LST_NM,
    :PARTY_LOC,
    :PARTY_INCOME,
    :JDATE
);


.LOGOFF
.QUIT